import LocalizedStrings from 'react-native-localization';

const strings = {
  en: {
    "categories": "categories",
    "account": "Account",
    "orders": "Orders",
    "favorites": "Favorites",
    "language": "language",
    "contactUS": "contact with us",
    "checkOut": "checkout",
    "selectSize": "Select Size ",
    "search": "Search for ...",
    "address": "Address",
    "signOut": "Sign Out",
    "addToCart": "Add to cart",
    "description": "Description",
    "areYouMember": "Are you member?",
    "login": "login",
    "register-now": "Register Now!",
    "email": "Email",
    "password": "Password",
    "full-name": "full Name",
    "or": "Or",
    "register": "Register",
    "account": "Account",
    "information": "Inforamtion",
    "done": "Done",
    "fillInfo": "Please Fill your inforamtion",
    "city": "City",
    "street": "Street",
    "addressDesc": "Description for the address",
    "mobileNumber": "Mobile Number",
    "shipping-info": "Shipping Information",
    "totalAmount": "Total Amount",
    "remove": "Remove",
    "subtotal": "SUBTOTAL",
    "cart": "Cart",
    "phoneNumber": "Phone Number",
    "addToCart": "Add To Cart",
    "website": "WebSite",
    "name": "name",
    "orderderIn": "orderder in",
    "adresses": "Addresses",
    "edit": "Edit",
    "cancel": "Cancel",
    "size": "Size",
    "signOut": "Sign Out",
    "personalInformation": "Personal Information",
    "chooseYourLanguage": "Choose your language",
    "youHaveNoOrdersYet": "you have no orders yet",
    "youHaveNoFavoriteItems": "you have no favorite items",
    "continueShopping": "Continue Shopping",
    "viewCart": "View Cart",
    "awesomeChoise": "Awesome Choice",
    "WhatDoYouWantToDoNow": "What do you want to do now ?",
    "quantity": "Quantity",
    "youHaveNoItemsYet": "you have no items yet",
    "JD": "JD",
    "changeTheLanguage": "Change The Language",
    "areYouSureYouWantToChangeTheLanguage": "are you sure you want to change the language ?",
    "yes": "Yes"
  },
  ar: {
    "categories": "الفئات",
    "cancel": "إغلاق",
    "addToCart": "إضافة إلى السلة",
    "account": "الحساب",
    "orders": "الطلبات",
    "favorites": "المفضلة",
    "language": "اللغة",
    "contactUS": "إتصل بنا ",
    "checkOut": "الدفع",
    "selectSize": "إختر الحجم ",
    "search": "ابحث عن ...",
    "address": "العنوان",
    "signOut": "تسحيل خروج",
    "addToCart": "إضافة الى السلة",
    "description": "الوصف",
    "areYouMember": "هل انت عضو؟",
    "login": "تسجيل دخول",
    "register-now": "التسجيل الان!",
    "email": "البريد الالكتروني",
    "password": "الرقم السري",
    "size": "الحجم",
    "fullName": "الاسم الكامل",
    "or": "أو",
    "register": "التسجيل",
    "account": "الحساب",
    "information": "معلومات",
    "done": "تم",
    "fillInfo": "الرجاء ادخال جميع المعلومات ",
    "city": "المدينة",
    "street": "الشارع ",
    "addressDesc": "نفاصيل عن العنواو ",
    "mobileNumber": "رقم الهاتف ",
    "shippingInfo": "Shipping Information",
    "totalAmount": "Total Amount",
    "remove": "حذف",
    "subtotal": "المبلغ الإجمالي",
    "cart": "السلة ",
    "phoneNumber": "رقم الهاتف",
    "website": "الموقع الالكتروني",
    "name": "الاسم",
    "orderderIn": "تاريخ الطلب",
    "quantity": "الكمية",
    "adresses": "الموقع",
    "edit": "تعديل",
    "signOut": "تسجيل خروج",
    "personalInformation": "معلومات الحساب",
    "chooseYourLanguage": "إختر لغة التطبيق",
    "youHaveNoOrdersYet": "لا يوجد طلبات",
    "youHaveNoFavoriteItems": "لا يوجد لديك عناصر مفضلة",
    "continueShopping": "مواصلة التسوق",
    "viewCart": "عرض السلة",
    "awesomeChoise": "اختيار رائع",
    "WhatDoYouWantToDoNow": "ماذا تريد ان تفعل الآن ؟",
    "youHaveNoItemsYet": "لا يوجد لديك عناصر حتى الآن",
    "JD": "دينار",
    "changeTheLanguage": "تغيير اللغة",
    "areYouSureYouWantToChangeTheLanguage": "هل انت متأكد أنك تريد تغيير اللغة ؟",
    "yes": "نعم"


  }
}
export default strings
